name: Build and Deploy

on:
  push:
    branches: [master]

env:
  APPNAME: bot
  
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Create Docker Context
      run: |
        docker context create builders
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
       endpoint: builders
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and Push to Github Packages
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/destinyarena/discord-bot:latest
          ghcr.io/destinyarena/discord-bot:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
    - name: Checkout Helm Repo
      uses: actions/checkout@v2
      with:
        repository: destinyarena/helm-charts
        token: ${{ secrets.DESTINYARENA_ACTIONS }}
    - uses: chrisdickinson/setup-yq@latest
    - name: Update the Helm Chart values.yaml
      run: |
        yq w -i values.yaml ${{ env.APPNAME }}.image.tag ${{ github.sha }}
    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Updating Image Tag: ${{ github.sha }}"
        git push origin master
